// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDigK69b-7HfwLS4RvDMBeJ202lAS7hA1k',
    appId: '1:1047614152833:web:80cb48fc6ad7043786ad80',
    messagingSenderId: '1047614152833',
    projectId: 'college-hearts',
    authDomain: 'college-hearts.firebaseapp.com',
    storageBucket: 'college-hearts.firebasestorage.app',
    measurementId: 'G-15MQ0F5JTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFxlTpU8lV9kjtyweVVU37S00WAujR0F4',
    appId: '1:1047614152833:android:54d825ade8bc478a86ad80',
    messagingSenderId: '1047614152833',
    projectId: 'college-hearts',
    storageBucket: 'college-hearts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtlWjMgepjXTcUj45rGGRjk7f3Kasfa8Y',
    appId: '1:1047614152833:ios:678293ec5e8930aa86ad80',
    messagingSenderId: '1047614152833',
    projectId: 'college-hearts',
    storageBucket: 'college-hearts.firebasestorage.app',
    iosBundleId: 'com.collegehearts.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtlWjMgepjXTcUj45rGGRjk7f3Kasfa8Y',
    appId: '1:1047614152833:ios:678293ec5e8930aa86ad80',
    messagingSenderId: '1047614152833',
    projectId: 'college-hearts',
    storageBucket: 'college-hearts.firebasestorage.app',
    iosBundleId: 'com.collegehearts.newapp',
  );

}